apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: student-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FUQ0NBVkVDQVFBd0pERVFNQTRHQTFVRUF3d0hjM1IxWkdWdWRERVFNQTRHQTFVRUNnd0hiR1ZoY201bApjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOS1NvSWFMRzlrRllnUS81c09MClpqZHpLU1BGa3ZZY2Ivd2VVWC9HVUhub3FtcFVJamYrdGRiVzFkWm5PWHRUaTJoNHE4RWlmNS9aY2tQNmRRMlIKYzFjbGxjZDhWMmk3Q2k5TnlpSkI0bHBpRDV6T09vUGtsVmg2NDl5T215ZUVhSkx6RDR1akFzRHhIZGkvWkhlMApNOExqcnJmbTExcW5hRUo2ZVQwSHNZYnZYdjQwY0hQM3VnU0FmUmNMVUxLZ0xWN2JxQW81eFovcUVhZ3JZeHlxCmNlM1JqTnduL1AwY1Q2T0hOUUdORVVzYUVmNW5BdVdOaHRqWVMveHhGb1RUMU1EeVZWNk5VcHhmTkVRbFR6dU4KTkVoZTc3OWM5bmR6MEtwRkxKd3RRME9IcDVVenBYTEg0WVNnNHBlNkpCaHhNRXNuQitjdC84YXpZOWFFbGJTdApnbGNDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUI4NTNhZ25PWk1pWTBTM0gzUGFidElkb0N5ClFsaVNBcnhyNnREN2J1UmRxeVlIZnNPUU5EdFNpY2psNTRzaE1RaVRPNGswVHB1N0pWeVhwMlh3aVB4YXVZR00KbEpkU0ROS2lYS2V5dVlrR1NLeFlBU1ljZVlyYzgxVGlqUzM5ZEJQbDljVzBqdnhzWUN3L1N0QWYvTGd5UnU1YwpTL0YyNXI5RUVWbnN0OUN1ZlpkdFEwZmZuVGVqNS9qUGhIbkFQTnJtVWRrb1AyVWh3WmJ0K2s1YllQK1ltZXJmCmhmdmhPanhiQXlvL09zNmxZbTdBVWlOZE9JK28xdWVUK2VCRWwzMktnSVpzZkk0aXVwckI3NmVTVFZMRWxwSTUKSmZkZGJOc3NoMXhUdEo1c2Z1V0xTMG03c1crY2EzeXc3OUpzaDZhOHhHWThSeGxYRmJXUlhHTU9vMnZaCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
