apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-green
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-webserver-green
  template:
    metadata:
      labels:
        app: nginx-webserver-green
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          command: [ "/bin/sh", "-c", "sed -i 's/<body>/<body style=\"background-color:green;\">/' /usr/share/nginx/html/index.html; nginx -g 'daemon off;'" ]
          ports:
          - containerPort: 80
