apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: nginx
    image: nginx
    command: [ "/bin/sh", "-c", "echo $(DATA_STRING) > $(DATA_PATH); nginx -g 'daemon off;'" ]
    env:
      - name: DATA_STRING
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: STRING
            optional: true
      - name: DATA_PATH
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: PATH
            optional: true
  restartPolicy: Never