apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    key: val
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
